FROM alpine:3.16
ARG	MYSQL_PASSWORD \
	MYSQL_DATABASE \
	MYSQL_USER \
	MYSQL_NAME
RUN apk update && \
		apk upgrade && \
		apk add --no-cache mariadb mariadb-client
# COPY db.sh .
# RUN chmod +x mariadb.sh && \
# 		sh db.sh && \
# 		rm db.sh
USER	mysql
CMD mysqld_safe && tail -f /dev/null
