# FROM alpine:3.16

FROM debian:buster

ENV debian_release="buster"

RUN apt-get update \
  && apt-get install -y systemd ca-certificates nginx

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

RUN apt-get update \
  && apt-get install openssl

COPY config.sh .
RUN bash config.sh

RUN adduser --system --group --no-create-home nginx

CMD ["/usr/sbin/nginx"]