# FROM alpine:3.16

FROM debian:buster

# ENV debian_release="buster"

RUN apt-get update \
  && apt-get install -y systemd ca-certificates nginx openssl

COPY nginx.conf /etc/nginx/nginx.conf
COPY default.conf /etc/nginx/conf.d/default.conf

# COPY config.sh .
# RUN bash config.sh

RUN mkdir /etc/nginx/ssl
RUN openssl genrsa -out /etc/nginx/ssl/server.key
RUN openssl req -new -key /etc/nginx/ssl/server.key -out /etc/nginx/ssl/server.csr -subj "/CN=example.com"
RUN openssl x509 -req -signkey /etc/nginx/ssl/server.key -in /etc/nginx/ssl/server.csr -out /etc/nginx/ssl/server.crt

RUN adduser --system --group --no-create-home nginx

CMD ["/usr/sbin/nginx"]