version: '3'

services:
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: nginx
    depends_on:
      - wp
    ports:
      - "443:443"
    networks:
      - inception
    restart: unless-stopped
    volumes:
      - wp-volume:/var/www/

  db:
    image: mariadb
    container_name: mariadb
    build:
      context: db
      args:
        DB_PASS: ${DB_PASS}
        DB_DATABASE: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
    
    expose:
      - "3306"

    networks:
      - inception

    restart: unless-stopped
    volumes:
      - db-volume:/var/lib/mysql

  wp:
    image: wordpress
    container_name: wordpress
    restart: unless-stopped
    build:
      context: wordpress
    expose:
      - "9000"
    env_file: .env
    depends_on:
      - db
    networks:
      - inception
    volumes:
      - wp-volume:/var/www/
    #dockerコンテナ内の　var/wwwに紐付ける

networks:
  inception:

volumes:
  wp-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/satushi/data/wordpress

  db-volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/satushi/data/mariadb

#restartpolicyにはいろいろあって
# no：再起動しない
# always：常に再起動する
# on-failure：エラーで終了した場合に再起動する
# unless-stopped：明示的に停止されるまで再起動する
#のようになってるっぽい
