version: '3'

services:
  nginx:
    image: nginx
    container_name: "nginx"
    build:
      context: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - docker-network
    restart: always
    volumes:
      - wordpress:/var/www/html/wordpress

  mariadb:
    image: mariadb
    container_name: "mariadb"
    build: db
    
    expose:
      - "3306"

    networks:
      - docker-network

    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      WP_DATABASE_NAME: ${WP_DATABASE_NAME}
      WP_DATABASE_USER: ${WP_DATABASE_USER}
      WP_DATABASE_PASSWORD: ${WP_DATABASE_PASSWORD}

    healthcheck:
      test: mysql --protocol=tcp -u"$WP_DATABASE_USER" -p"$WP_DATABASE_PASSWORD" -hlocalhost --database="$WP_DATABASE_NAME" -e 'SELECT 1' &> /dev/null
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 10s

  wordpress:
    image: wordpress
    container_name: "wordpress"
    restart: always
    build: wordpress
    expose:
      - "9000"
    depends_on:
      - db
    networks:
      - docker-network
    volumes:
      - wordpress:/var/www/html/wordpress
    environment:
      WP_DB_HOST: mariadb
      WP_DB_USER: ${WP_DATABASE_USER}
      WP_DB_PASSWORD: ${WP_DATABASE_PASSWORD}
      WP_DB_NAME: ${WP_DATABASE_NAME}
      WP_TITLE: ${WP_TITLE}
      WP_ADMIN_USER: ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}
      WP_USER: ${WP_USER}
      WP_PASSWORD: ${WP_PASSWORD}
      WP_EMAIL: ${WP_EMAIL}

    healthcheck:
      test: wp core is-installed --allow-root --path=/var/www/html/wordpress &> /dev/null
      interval: 5s
      timeout: 30s
      retries: 10
      start_period: 30s

networks:
  docker-network:
    name: docker-network

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/satushi/data/wordpress

  mariadb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/satushi/data/mariadb

#restartpolicyにはいろいろあって
# no：再起動しない
# always：常に再起動する
# on-failure：エラーで終了した場合に再起動する
# unless-stopped：明示的に停止されるまで再起動する
#のようになってるっぽい
